### ISSUE TITLE
Januári beadandó

### ISSUE THREAD

**Issue by Sly122** [Teaching-projects/januari-beadando-Sly122#1]
Szép napot Tanár úr! 
Feltöltöttem a beadandómat, és arra kérném, hogy nézze meg. 
Plusz annyit szeretnék még, hogy megtudja -e mondani, hogy ez eddig egy hányast érdemelne, és hogy kell -e még rajta változtatnom/javítanom. (Slacken írt véleménye alapján változtattam a dolgokon.)

**Comment by hegyhati** [comment]
3 es 4 kozott 4 fele huzva. 

Tipp a bovitesre (az otoshoz): az irany mellett lenyeg egy olyan visszajelzes is, hogy mennyire kozel sikerult tippelni. (hideg: legalabb 10 messzire, langyos: 5-10, meleg: 3-4, forro: 1-2) 
Az pluszban jo volna, ha az elejen megkerdezne, hogy konnyu vagy nehez modban akarunk-e jatszani. Nehezben nem mondja ezeket a "homersekleteket", es kevesebb eletunk van.

Ami meg erdekel, hogy `while-else`-et es a `break`-et honnet tanultad, es erted-e mit csinal?

**Comment by hegyhati** [comment]
Jah, egy fontos dolog, az otos csak akkor, ha fuggvenybe ki van szervezve az, ami az iranyt/tavolsagot megmondja.

**Comment by Sly122** [comment]
Szép estét Tanár úr!
Kibővítettem a tippjei alapján.

**Comment by hegyhati** [comment]
Eleg kacifantos, sok mindent lehetne szepiteni rajta, de ezen most nem fogok rugozni. Ami viszont nem jo, hogy az osszes homersekletnel a `szam - tipp`-et nezed. Node ha nagyobbat tippelsz, mint a szam, akkor ez mindig negativ. Szoval nemcsak az egyik iranyba tud elterni 4-gyel pl, hanem a masik iranyba is. 

Ezt meg ha tudod, javitsd ki, de amugy meglesz az 5
